#! /bin/bash

[[ ! -x $1 ]] && echo "usage: OBFUSLATE-BINARY" && exit

bin=$1

url="http://pizzachili.dcc.uchile.cl/repcorpus"

suffix="gz"

paths="\
artificial/fib41 \
artificial/rs.13 \
artificial/tm29 \
pseudo-real/dna.001.1 \
pseudo-real/proteins.001.1 \
pseudo-real/english.001.2 \
real/Escherichia_Coli \
real/kernel \
real/world_leaders"

workdir="t"

mkdir $workdir 2> /dev/null

for path in $paths
do
    file=$(basename $path)

    gz=$file.$suffix

    echo "Testing $path."

    echo "Downloading."
    wget -q -P $workdir -c $url/$path.$suffix

    echo "Decompressing (zcat)."
    zcat $workdir/$gz > $workdir/$file

    echo "Decompressing (obfuslate)."
    ./$bin < $workdir/$gz > $workdir/output

    echo "Comparing output."
    cmp $workdir/$file $workdir/output 2> /dev/null

    if [ "$?" == 0 ]; then
        echo -e "\033[1m[PASSED]\033[0m"
    else
        echo -e "\033[1;31m[FAILED] -- \$? = $?\033[0m"
    fi

    echo
done
