#! /bin/bash
. $(dirname $0)/test-shared || exit

[[ ! -x $1 ]] && echo "usage: OBFUSLATE-BINARY" && exit

bin=$1

url="http://pizzachili.dcc.uchile.cl/repcorpus"

texts="\
artificial/fib41 \
artificial/rs.13 \
artificial/tm29 \
pseudo-real/dna.001.1 \
pseudo-real/proteins.001.1 \
pseudo-real/english.001.2 \
real/Escherichia_Coli \
real/kernel \
real/world_leaders"

for text in $texts
do
    file=$(basename $text)

    echo "Testing $text."

    [[ ! -f "$workdir/${file}.gz" ]] && fetch $url $text

    check $bin $file
done
